
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=dpg-d0pmk56mcj7s73eaupd0-a
      - DB_PORT=5432
      - DB_USER=elisee
      - DB_PASSWORD=a0u3mIs81CFQ11daiCmnioM55vWxaMOW
      - DB_NAME=ticketing_zng0
    volumes:
      - .:/projet_ticketing

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a0u3mIs81CFQ11daiCmnioM55vWxaMOW
      MYSQL_DATABASE: ticketing_zng0
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
