
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=dpg-d2mpcq6r433s73avghb0-a
      - DB_PORT=5432
      - DB_USER=ticketing_xvoq_user
      - DB_PASSWORD=8qkPANbuhRWe0gLi78Kvjb1wAhz89Hdu
      - DB_NAME=ticketing_xvoq
    volumes:
      - .:/projet_ticketing

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8qkPANbuhRWe0gLi78Kvjb1wAhz89Hdu
      MYSQL_DATABASE: ticketing_xvoq
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
