"""Ajout champ is_read dans Message

Revision ID: 465f92aa2802
Revises: 
Create Date: 2025-05-14 17:45:22.887945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465f92aa2802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
