"""Ajout du champ image_path à Ticket

Revision ID: d8fe132ce8f9
Revises: 465f92aa2802
Create Date: 2025-05-14 23:06:46.391501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fe132ce8f9'
down_revision = '465f92aa2802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
